#ifndef __ASM_OFFSETS_H__
#define __ASM_OFFSETS_H__
/*
 * DO NOT MODIFY.
 *
 * This file was generated by /home/guohr/workdir/gulessoft/linux/trunk/Kbuild
 *
 */

#define SIZEOF_STRUCT_PT_REGS 164 /* sizeof(struct pt_regs) */
#define SIZEOF_STRUCT_SWITCH_STACK 132 /* sizeof(struct switch_stack) */
#define OFFSET_KSP_THREAD_INFO 40 /* offsetof(struct thread_info,ksp) */
#define OFFSETOF_TASK_THREAD_INFO 0 /* offsetof(struct thread_info,task) */
#define SIZEOF_SYSCALL_ARGS 24 /* 6*sizeof(unsigned long) */
#define PAGE_SIZE_ORDER_PLUS_THREAD_SIZE_ORDER 13 /* PAGE_SHIFT+THREAD_SIZE_ORDER */
#define __NR_sigreturn 119 /* __NR_sigreturn */
#define __NR_rt_sigreturn 173 /* __NR_rt_sigreturn */
#define __NR_clone 120 /* __NR_clone */
#define NR_syscalls 289 /* NR_syscalls */

#endif
